micronaut.application.name=gamers_community
micronaut.server.port=8080



# Security Configuration
micronaut.security.authentication=bearer
micronaut.security.reject-not-found=false
micronaut.security.token.jwt.signatures.secret.generator.secret=vbrhLJRSTDAR456TQRCHZRB892517ZzdtaAartutkwD23ar
micronaut.security.token.jwt.signatures.secret.generator.jws-algorithm=HS256
micronaut.security.endpoints.login.enabled=true
micronaut.security.endpoints.login.path=/api/auth/login
micronaut.security.endpoints.logout.enabled=true
micronaut.security.endpoints.logout.path=/api/auth/logout

# Database Configuration
datasources.default.url=jdbc:mysql://localhost:3306/wogg_mysql_db
datasources.default.driverClassName=com.mysql.cj.jdbc.Driver
datasources.default.username=${DB_USERNAME:root}
datasources.default.password=${DB_PASSWORD:Olschool230187r}
datasources.default.dialect=MYSQL
datasources.default.pool.initial-size=10
datasources.default.pool.max-size=20
datasources.default.pool.min-size=5

# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true

# Logging Configuration
logger.level.io.micronaut.http.server.netty=DEBUG
logger.level.io.netty.handler.logging=DEBUG

# Access logging
micronaut.server.netty.access-logger.enabled=true

